# DeepSeek API
deepseek.api-key=${DEEPSEEK_API_KEY}

# embedding API
dashscope.embedding.api-key=${DASHSCOPE_EMBEDDING_API_KEY}

# GitHub
github.token=${GITHUB_TOKEN}

# Webhook
webhook.secret=${WEBHOOK_SECRET}

# Qdrant
qdrant.api-key=${QDRANT_API_KEY}
qdrant.host=localhost
qdrant.port=6334
qdrant.collection-name=code_review_agent
