# DeepSeek API
deepseek.api-key=sk-d4a3f5b02587464e99d1b40a72983961

# 阿里云 embedding API
dashscope.embedding.api-key=sk-ws-H.REDDHEE.drII.MEUCIEEvL6xC9z5pL1DAJkcbATN37d8da1t5NUgbMFnNBoGoAiEA4ItB_PA3lpJYEzpHCJxrjPK1M2gSWM-csSP8lsxSFpk

# Qdrant (本地开发)
qdrant.host=localhost
qdrant.port=6334
qdrant.collection-name=code_review_agent
